-- MySQL Script generated by MySQL Workbench
-- Sat Oct 17 00:15:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema congeladosgodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema congeladosgodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `congeladosgodb` DEFAULT CHARACTER SET utf8 ;
USE `congeladosgodb` ;

-- -----------------------------------------------------
-- Table `congeladosgodb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congeladosgodb`.`categorias` (
  `idCategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `congeladosgodb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congeladosgodb`.`productos` (
  `idProductos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(1000) NULL DEFAULT NULL,
  `catidadVentas` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(10,0) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `idCategorias` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `idCategorias_idx` (`idCategorias` ASC),
  CONSTRAINT `idCategorias`
    FOREIGN KEY (`idCategorias`)
    REFERENCES `congeladosgodb`.`categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `congeladosgodb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congeladosgodb`.`usuarios` (
  `idUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `contraseña` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` VARCHAR (45) NULL DEFAULT NULL,
  `ciudad` varchar(45) NOT NULL,
  `fecha` NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `congeladosgodb`.`mediodepago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congeladosgodb`.`mediodepago` (
  `idMedioDePago` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMedioDePago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `congeladosgodb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congeladosgodb`.`ventas` (
  `idVentas` INT(11) NOT NULL AUTO_INCREMENT,
  `totalDeVenta` DECIMAL(10,0) NULL DEFAULT NULL,
  `idUsuarios` INT(11) NULL DEFAULT NULL,
  `idMedioDePago` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `idMedioDePagoFK_idx` (`idMedioDePago` ASC),
  INDEX `idUsuariosFK` (`idUsuarios` ASC),
  CONSTRAINT `idMedioDePagoFK`
    FOREIGN KEY (`idMedioDePago`)
    REFERENCES `congeladosgodb`.`mediodepago` (`idMedioDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuariosFK`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `congeladosgodb`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `congeladosgodb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `congeladosgodb`.`carrito` (
  `idCarrito` INT(11) NOT NULL AUTO_INCREMENT,
  `idVentas` INT(11) NULL DEFAULT NULL,
  `idProductos` INT(11) NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `idProductosFK_idx` (`idProductos` ASC),
  INDEX `idVentasFK_idx` (`idVentas` ASC),
  INDEX `idUsuarioFK_idx` (`idUsuario` ASC),
  CONSTRAINT `idProductosFK`
    FOREIGN KEY (`idProductos`)
    REFERENCES `congeladosgodb`.`productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuarioFK`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `congeladosgodb`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVentasFK`
    FOREIGN KEY (`idVentas`)
    REFERENCES `congeladosgodb`.`ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
